### ISSUE TITLE
Criar cadastro de espécie

### ISSUE THREAD

**Issue by MaironCosta** [petshop-system/petshop-admin-api#4]
**Contexto**

Criar cadastro de espécie.

**Descrição**

Eu, como desenvolvedor, solicito que seja desenvolvido o cadastro de espécie. Toda espécie deve ter um nome.

**Comment by gustavojustino** [comment]
Em andamento

**Comment by gustavojustino** [comment]
Esta issue implementou a feature 'consultas de espécie (getByID)' da issue #5
